### PR TITLE
Allow multiple users creation from hiera settings in different hierarchy, fix #24

### LINKED ISSUE #24: Creating multiple users using different classifications doesn't work?
I am having trouble creating different users in different environments using hiera classifications.

hiera.yaml:
https://gist.github.com/jceloria/790ca984847166c83ffa#file-hiera-yaml

defaults.yaml:
https://gist.github.com/jceloria/6b5c9606418e37999e07#file-defaults-yaml

hostA.yaml:
https://gist.github.com/jceloria/9af876cabd8682469d9b#file-hosta-yaml

Unless I put all users in the same accounts:users stanza then only the first matching classification in this case (defaults.yaml) and the rest of the user accounts are ignored.

### PR DESCRIPTION
**Pull request by salimane**

### CODE REVIEW

**Comment by deric** [comment]
Dejavu. Right, for further reference the change was introduced in [this commit](https://github.com/deric/puppet-accounts/commit/ee29b0de1be48ea60fefea7df518d54df6fe5da2). I'm ok with reverting this change. As you can see from the Travis build this change will break installations on Puppet 2.7. We need to write better tests for this.

**Comment by deric** [comment]
Ok, now it should work. I've added `puppet-hiera` requirement for Puppet 2.7. This requirement was there before [1.1.3](https://github.com/deric/puppet-accounts/releases/tag/v1.1.3) release. So this would possibly break only installations running on the latest version.

**Comment by deric** [comment]
The reason for introducing the fix was issue #14, I should have written that into commit message.

**Comment by salimane** [comment]
@deric :+1:

**Comment by deric** [comment]
Released as [v1.2.0](https://github.com/deric/puppet-accounts/releases/tag/v1.2.0).

**Pull request merged**
